#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightIR,        sensorReflection)
#pragma config(Sensor, in2,    leftIR,         sensorReflection)
#pragma config(Sensor, dgtl2,  leftButton,     sensorTouch)
#pragma config(Sensor, dgtl10, RedLED,         sensorDigitalOut)
#pragma config(Sensor, dgtl11, SONAR,          sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port2,           motorPayload,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Threshold of value read by IR-sensor circuit.
const   int THRESHOLDL = 110;
const   int THRESHOLDR = 900;


//Initializing the machines possible states (standby,clearance,detection,approach,deliver,park).
enum systemState{standby,clearance,detection,approach,deliver,park};

//Robot stop method - sets both motors power to 0
void stopMovement(){
	motor[rightMotor] = 0;
  motor[leftMotor] = 0;
}

//Robot reversal method - sets both motors to reverse at a specified speed for a specified distance
// parameters - reversal speed | reversal distance
void reverse(int speed,int distance){
	resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);
 	while(getMotorEncoder(leftMotor) > -20*distance){
 		motor[rightMotor] = -speed;
   		 motor[leftMotor] = -speed;
	}
	stopMovement();
}

// robot spin method - sets motor power at a specified speed one going forward and the other in reverse so it conducts a point turn
// Parameters - turn speed | turn direction 1 = left, 0 = right
void spin(int speed, int direction){
	if(direction == 1){
		motor[leftMotor] =	-speed;
		motor[rightMotor] =	speed;
	}
	if(direction == 0){
		motor[leftMotor] = speed;
		motor[rightMotor] =	-speed;
	}
}

// Robot spin method for angles - the same as previous spin method but only spins for a specified amount of time.
// Parameters - turn speed | angle to turn | turn direction 1 = left 0 = right
void spinA(int speed, int angle, int direction){
	resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);
  	if(direction == 1){
			while(getMotorEncoder(leftMotor) > -angle*1.74){
				motor[leftMotor] =	-speed*1.2;
				motor[rightMotor] =	speed;
			}
			stopMovement();
		}
		if(direction == 0){
			while(getMotorEncoder(leftMotor) < angle*1.74){
				motor[leftMotor] = speed;
				motor[rightMotor] =	-speed;
			}
			stopMovement();
		}
}

//Robot moving forward method - sets motor to a specified speed value going forward
//Parameters - Robot speed
void forward(int speed){
	motor[rightMotor] = speed;
  motor[leftMotor] = speed;
}

// Robot repositioning method - reorients its self after initial target detection
//Parameters - distance to travel | which sensor to use 1 = left IR sensor, 0 = right IR sensor
void check(int dist , int sensor){
	
	//conducts operation using values read by the left IR sensor
	if(sensor == 1){
	while(SensorValue[SONAR] > dist/2 && SensorValue[SONAR] >= 0 ){ // moves forward half the distance specified
		forward(30);
	}
		stopMovement();
		wait1Msec(100);
		spinA(15, 90, 1); // spins left  until it no longer detects the IR light so it can find the target and update its trajectory

	while(SensorValue[leftIR] > THRESHOLDL){ // spins left until it detects target
		spin(30, 1);
	}
	stopMovement();
	wait1Msec(100);
	}
	
	//conducts operation using values read by the right IR sensor
	if(sensor == 0){
	while(SensorValue[SONAR] > dist/2 && SensorValue[SONAR] >= 0 ){ //moves forward half the distance specified
		forward(30);
	}
		stopMovement();
		wait1Msec(100);
		spinA(15, 90, 1); // spins left  until it no longer detects the IR light so it can find the target and update its trajectory

	while(SensorValue[rightIR] > THRESHOLDR){  // spins left until it detects target
		spin(30, 1);
	}
	stopMovement();
	wait1Msec(100);
	}
 }

task main()
{
	//initializing system state at first state (standby) when robot is powered on.
	systemState currentState = standby;

	//loop to cycle through all states
 while(true){

 	// checking which state the robot is in.
 	switch(currentState){

 	//first state standby - robot awaits left button press to begin actions.
 	case(standby):
 			while(true){
 				if(SensorValue(leftButton) == 1){
 					SensorValue[RedLED] = 0;   //turns red LED off
 					currentState = clearance; // changes state to clearance state
 					break;
 				}
 			}

 			// second state clearance - robot checks if it is not too close to wall that it is facing.
 			case(clearance):

 			//checks proximity to wall. if closer than 12 cm reverses 15 cm away from the wall.
 			if(SensorValue[SONAR] < 12 && SensorValue[SONAR] >= 0 ){
 				reverse(30,15); 
 			}
 				wait1Msec(400); 
 			currentState = detection; // changes state to detection state
 			break;

 			//third state detection - robot spins until specified IR sensors detect IR light from target
 			case(detection):
 				wait1Msec(1000);
 				while(SensorValue[rightIR] > THRESHOLDR){ // spins left until it detects the IR light and then stops
 					spin(30,1); 
					}
					stopMovement();
					wait1Msec(1000);
					currentState = approach; // changes state to approach state
  				break;

 			// fourth state - robot approaches target after detecting target.
			case(approach):

				int d = SensorValue[SONAR]; // records initial distance from target
				check(d,0); // moves forward half of distance d and readjusts its path
			
					while(SensorValue[SONAR] > 6 && SensorValue[SONAR] >= 0 ){ // moves forward until 6 cm away from the target
						forward(30);
					}
					stopMovement();
					wait1Msec(600);
					currentState = deliver; // changes state to deliver state
					break;

			// fifth state - robot delivers its payload
			case(deliver):

				// payload motor turns pushing rack gear forward which pushes the payload off of the platform onto the target.
				// payload motor then reverses and resets rack gear positioning
				motor[ motorPayload] = 30;
  				wait1Msec(900);
  				motor[ motorPayload] = 0;
  				wait1Msec(900);
  				motor[ motorPayload] = -30;
  					wait1Msec(950);
  				motor[ motorPayload] = 0;
  				currentState = park; // changes state to park state
  				break;

					// sixth and final state - robot distances its self from the target and parks infront of one of the arena walls
  				case(park):

  				reverse(30, 10); // reverses for 10 cm
  				spin(30,1); // spins facing away from target
  				wait1Msec(2800);
				forward(30);

				// robot moves forward untill it is 20 cm away from one of the arena walls, stops and turns on a red LED to signal completion.
  				while(true){
  					if(SensorValue[SONAR] < 20 && SensorValue[SONAR] >= 0 ){
  						stopMovement();
  						SensorValue[RedLED] = 1; // turn on red LED.
  						currentState = standby; // changes state to standby state to begin process once again
  						break;
  					}
  				}
  		}
	}
}
