#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  rightButton,    sensorTouch)
#pragma config(Sensor, dgtl2,  leftButton,     sensorTouch)
#pragma config(Sensor, dgtl11, SONAR,          sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(true){
  	if(SensorValue(leftButton) == 1){
  		resetMotorEncoder(leftMotor);
  		resetMotorEncoder(rightMotor);
 		  while(getMotorEncoder(leftMotor) < 1800){
  				motor[rightMotor] = 63;
    			motor[leftMotor] = 63;
  	}
  		motor[rightMotor] = 0;
  		motor[leftMotor] = 0;
  	}
		if(SensorValue(rightButton) == 1){
			motor[leftMotor] =	-63;
			motor[rightMotor] =	63;
			wait1Msec(1400);
			motor[rightMotor] = 0;
  		motor[leftMotor] = 0;
		}
 }
}
