#pragma config(Sensor, dgtl1,  rightButton,    sensorTouch)
#pragma config(Motor,  port2,           motorBall,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
  		if(SensorValue(rightButton) == 1){
  				motor[ motorBall] = 30;
  				wait1Msec(900);
  				motor[ motorBall] = 0;
  				wait1Msec(900);
  				motor[ motorBall] = -30;
  					wait1Msec(950);
  				motor[ motorBall] = 0;

  		}
	}
}
